=== IkerPoza/EjerciciosLenguaje/XSD/Prácticas 1, 2 y 3-20260312/Practica2/transporte1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transporte" type="tTransporte"/>
    <xs:complexType name="tTransporte">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="coche" type="xs:string"/>
            <xs:element name="tren" type="xs:string"/>
            <xs:element name="avion" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:schema>

=== IkerPoza/EjerciciosLenguaje/XSD/Prácticas 1, 2 y 3-20260312/Practica2/transporte1.xml
<?xml version="1.0" encoding="UTF-8"?>
<transporte 
    xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "transporte1.xsd">
      <coche>Renault R23</coche>
      <tren>Talgo</tren>
      <tren>Alvia</tren>
      <avion>Boing</avion>
      <coche>Renault R7</coche>
      <avion>Boing</avion>
      <avion>Boing</avion>
</transporte>
