=== IkerPoza/EjerciciosLenguaje/Repaso/listado.dtd
<!ELEMENT listado (futuro+,divisa+,bono+,letra+)>

<!ELEMENT ciudad_procedencia (madrid|nueva_york|frankfurt|tokio)>
<!ELEMENT madrid EMPTY>
<!ELEMENT nueva_york EMPTY>
<!ELEMENT frankfurt EMPTY>
<!ELEMENT tokio EMPTY>

<!ELEMENT futuro (producto,mercado?,ciudad_procedencia)>
<!ATTLIST futuro precio CDATA #REQUIRED>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>

<!ELEMENT divisa (nombre_divisa,tipo_de_cambio*,ciudad_procedencia)>
<!ATTLIST divisa precio CDATA #REQUIRED>
<!ATTLIST divisa estable (si|no) #IMPLIED>
<!ELEMENT nombre_divisa (#PCDATA)>
<!ELEMENT tipo_de_cambio (#PCDATA)>

<!ELEMENT bono (pais_de_procedencia,valor_deseado,valor_minimo,valor_maximo,ciudad_procedencia)>
<!ATTLIST bono precio CDATA #REQUIRED>
<!ATTLIST bono estable CDATA #IMPLIED>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valor_deseado (#PCDATA)>
<!ELEMENT valor_minimo (#PCDATA)>
<!ELEMENT valor_maximo (#PCDATA)>

<!ELEMENT letra (tipo_de_interes, pais_emisor, ciudad_procedencia)>
<!ATTLIST letra precio CDATA #REQUIRED>
<!ELEMENT tipo_de_interes (#PCDATA)>
<!ELEMENT pais_emisor (espania|eeuu|alemania|japon)>
<!ELEMENT espania EMPTY>
<!ELEMENT eeuu EMPTY>
<!ELEMENT alemania EMPTY>
<!ELEMENT japon EMPTY>

=== IkerPoza/EjerciciosLenguaje/Repaso/listado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listado SYSTEM "listado.dtd">
<listado>
        <futuro precio="11.28">
                <producto>Cafe</producto>
                <mercado>América Latina</mercado>
                <ciudad_procedencia>
                        <frankfurt/>
                </ciudad_procedencia>
        </futuro>
        <divisa precio="183">
                <nombre_divisa>Libra esterlina</nombre_divisa>
                <tipo_de_cambio>2.7:1 euros</tipo_de_cambio>
                <tipo_de_cambio>1:0.87 dólares</tipo_de_cambio>
                <ciudad_procedencia>
                        <madrid/>
                </ciudad_procedencia>
        </divisa>
        <bono  precio="10000" estable="si">
                <pais_de_procedencia>Islandia</pais_de_procedencia>
                <valor_deseado>9980</valor_deseado>
                <valor_minimo>9950</valor_minimo>
                <valor_maximo>10020</valor_maximo>
                <ciudad_procedencia>
                        <tokio/>
                </ciudad_procedencia>
        </bono>
        <letra   precio="45020">
                <tipo_de_interes>4.54%</tipo_de_interes>
                <pais_emisor>
                        <espania/>
                </pais_emisor>
                <ciudad_procedencia>
                        <madrid/>
                </ciudad_procedencia>
        </letra>
</listado>
