=== IkerPoza/EjerciciosLenguaje/DTD/Practica7/practica7.dtd
<!ELEMENT facturas (factura)>
<!ELEMENT factura (emision, vendedor, cliente, articulo+, descuento?)>
<!ELEMENT emision (#PCDATA)>
<!ELEMENT vendedor (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cliente (nombre, direccion, telefono*)>
<!ELEMENT direccion (via, cp, localidad, provincia)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefono EMPTY>
<!ELEMENT articulo (denominacion, precio, cantidad)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
<!ATTLIST factura id ID #REQUIRED>
<!ATTLIST vendedor id ID #REQUIRED>
<!ATTLIST cliente id ID #REQUIRED>
<!ATTLIST telefono num NMTOKEN #REQUIRED>
<!ATTLIST articulo id ID #REQUIRED iva CDATA #REQUIRED>

=== IkerPoza/EjerciciosLenguaje/DTD/Practica7/practica7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "practica7.dtd">
<facturas>
      <factura id="f876">
            <emision>2012-02-28T08:25:02</emision> 
            <vendedor id="v12">
                  <nombre>Felix Aguirre Saez</nombre> 
            </vendedor>
            <cliente id="c9878">
                  <nombre>Igor Udiaga Lopez</nombre> 
                  <direccion>
                        <via>Calle Alonso Cano, 2, 3º A</via> 
                        <cp>41700</cp> 
                        <localidad>Deusto</localidad> 
                        <provincia>Vizcaya</provincia> 
                  </direccion>
                  <telefono num="666111666" /> 
                  <telefono num="954666111" /> 
            </cliente>
            <articulo id="a121" iva="18">
                  <denominacion>Silla giratoria modelo C-121</denominacion> 
                  <precio>98.23</precio> 
                  <cantidad>1</cantidad> 
            </articulo>
            <articulo id="a1124" iva="18">
                  <denominacion>Lámpara mesa con pantalla naranja modelo AK</denominacion> 
                  <precio>23.12</precio> 
                  <cantidad>2</cantidad> 
            </articulo>
            <descuento>20</descuento> 
      </factura>
</facturas>
