=== IkerPoza/EjerciciosLenguaje/XSD/Practica 7/mediateca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mediateca" type="tMediateca"/>
    <xs:complexType name="tMediateca">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="libro" type="tLibro"/>
                <xs:element name="pelicula" type="tPelicula"/>
            </xs:choice>
            <xs:element name="copyr" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tLibro">
        <xs:sequence>
            <xs:element name="titulo_l" type="xs:string"/>
            <xs:element name="autor" type="xs:string"/>
            <xs:element name="editor" type="tEditor"/>
        </xs:sequence>
        <xs:attribute name="idlibro" type="xs:ID" use="required"/>
        <xs:attribute name="prestado" type="tPrestado"/>
    </xs:complexType>

    <xs:simpleType name="tEditor">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Planeta"/>
            <xs:enumeration value="Rama"/>
            <xs:enumeration value="Circulo de Lectores"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tPrestado">
        <xs:restriction base="xs:string">
            <xs:enumeration value="si"/>
            <xs:enumeration value="no"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tPelicula">
        <xs:sequence>
            <xs:element name="titulo_p" type="xs:string"/>
            <xs:element name="director" type="xs:string"/>
            <xs:element name="estreno" type="tEstreno"/>
        </xs:sequence>
        <xs:attribute name="idpeli" type="xs:ID" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="tEstreno">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2012"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== IkerPoza/EjerciciosLenguaje/XSD/Practica 7/mediateca.xml
<?xml version="1.0" encoding="UTF-8"?>
<mediateca 
    xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "mediateca.xsd">
        <libro idlibro="l01" prestado="si">
              <titulo_l>Cien años de soledad</titulo_l>
              <autor>Gabriel Garcia Marquez</autor>
              <editor>Planeta</editor>
        </libro>
        <libro idlibro="l02" prestado="si">
              <titulo_l>Pantaleon y las Vistadoras</titulo_l>
              <autor>Mario Vargas LLosa</autor>
              <editor>Rama</editor>
        </libro>
        <libro idlibro="l04" prestado="no">
              <titulo_l>El nombre de la Rosa</titulo_l>
              <autor>Umberto Ecco</autor>
              <editor>Rama</editor>
        </libro>
        <libro idlibro="l05" prestado="si">
              <titulo_l>Las uvas de la ira</titulo_l>
              <autor>John Steinbeck</autor>
              <editor>Circulo de Lectores</editor>
        </libro>
        <libro idlibro="l06" prestado="no">
              <titulo_l>La Colmena</titulo_l>
              <autor>Camilo Jose Cela</autor>
              <editor>Planeta</editor>
        </libro>
        <pelicula idpeli="p01">
              <titulo_p>El verdugo</titulo_p>
              <director>berlanga</director>
              <estreno>1963</estreno>
        </pelicula>
        <libro idlibro="l03" prestado="no">
              <titulo_l>El ingenioso hidalgo Don Quijote de la Mancha</titulo_l>
              <autor>Miguel de Cervante</autor>
              <editor>Planeta</editor>
        </libro>
        <pelicula idpeli="p02">
              <titulo_p>Bienvenido, Mister Marshall</titulo_p>
              <director>berlanga</director>
              <estreno>1952</estreno>
        </pelicula>
        <pelicula idpeli="p03">
              <titulo_p>Apocalipsis Now</titulo_p>
              <director>Francis Ford Coppola</director>
              <estreno>1979</estreno>
        </pelicula>
        <pelicula idpeli="p04">
              <titulo_p>El Resplandor</titulo_p>
              <director>Stanley Kubrick</director>
              <estreno>1980</estreno>
        </pelicula>
        <pelicula idpeli="p05">
              <titulo_p>La escopeta nacional</titulo_p>
              <director>berlanga</director>
              <estreno>1977</estreno>
        </pelicula>
        <copyr>copyright</copyr>
</mediateca>
