=== IkerPoza/EjerciciosLenguaje/DTD/Practica8/plataforma.dtd
<!ELEMENT plataforma (curso+)>
<!ELEMENT curso (titulo, profesor+, modulos, estudiantes)>
<!ATTLIST curso id ID #REQUIRED nivel (basico|intemedio|avanzado) #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT profesor (nombre, email)>
<!ATTLIST profesor id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT modulos (modulo+)>
<!ATTLIST modulo id ID #REQUIRED>
<!ELEMENT modulo (nombre, leccion+)>
<!ATTLIST leccion refModulo IDREF #REQUIRED>
<!ELEMENT leccion (titulo, contenido, recursos?)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT recursos (recurso*)>
<!ELEMENT recurso EMPTY>
<!ATTLIST recurso tipo (video|pdf|web) #REQUIRED>
<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (nombre, email, progreso?, tutor)>
<!ATTLIST estudiante estado (activo|inactivo) #REQUIRED>
<!ELEMENT progreso (#PCDATA)>
<!ELEMENT tutor EMPTY>
<!ATTLIST tutor cod IDREFS #REQUIRED>

=== IkerPoza/EjerciciosLenguaje/DTD/Practica8/plataforma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plataforma SYSTEM "plataforma.dtd">
<plataforma>
    <curso id="c1" nivel="basico">
        <titulo>Introducción a XML</titulo>
        <profesor id="p1">
            <nombre>Ana López</nombre>
            <email>ana@academia.com</email>
        </profesor>
        <profesor id="p2">
            <nombre>Ekaitz Zambrana </nombre>
            <email>ezambrana@academia.com</email>
        </profesor>
        
        <modulos>
            <modulo id="m1">
                <nombre>Fundamentos</nombre>
                <leccion refModulo="m1">
                    <titulo>¿Qué es XML?</titulo>
                    <contenido>XML es un lenguaje de marcado.</contenido>
                    <recursos>
                        <recurso tipo="video"/>
                        <recurso tipo="pdf"/>
                    </recursos>
                </leccion>
                <leccion refModulo="m1">
                    <titulo>Estructura básica</titulo>
                    <contenido>Elementos, atributos y jerarquía.</contenido>
                </leccion>
            </modulo>
            <modulo id="m2">
                <nombre>DTD</nombre>
                <leccion refModulo="m2">
                    <titulo>Introducción a DTD</titulo>
                    <contenido>DTD define la estructura de un XML.</contenido>
                    <recursos>
                        <recurso tipo="web"/>
                    </recursos>
                </leccion>
            </modulo>
        </modulos>
        <estudiantes>
            <estudiante estado="activo">
                <nombre>Carlos Ruiz</nombre>
                <email>carlos@email.com</email>
                <progreso>75</progreso>
                <tutor cod="p1" />
            </estudiante>
            <estudiante estado="activo">
                <nombre>Lucía Pérez</nombre>
                <email>lucia@email.com</email>
                <tutor cod="p1" />
            </estudiante>
            <estudiante estado="inactivo">
                <nombre>Mario Gómez</nombre>
                <email>mario@email.com</email>
                <progreso>20</progreso>
                <tutor cod="p1 p2" />
            </estudiante>
        </estudiantes>
    </curso>
</plataforma>
