=== IkerPoza/EjerciciosLenguaje/DTD/Practica6/practica6.dtd
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, email*, relacion?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT relacion EMPTY>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona sexo (hombre|mujer) #IMPLIED>
<!ATTLIST relacion amigo_de IDREFS #IMPLIED>
<!ATTLIST relacion enemigo_de IDREFS #IMPLIED>

=== IkerPoza/EjerciciosLenguaje/DTD/Practica6/Practica6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "practica6.dtd">
<agenda>
    <persona id="p1">
        <nombre>Alberto</nombre>
        <email>albert@email.com</email>
        <relacion amigo_de="p2" />
    </persona>
    <persona id="p2">
        <nombre>Sandro</nombre>
        <relacion enemigo_de="p4" />
    </persona>
    <persona id="p3" sexo="mujer">
        <nombre>Maria</nombre>
        <email>maria@email.com</email>
    </persona>
    <persona id="p4">
        <nombre>Felipe</nombre>
        <relacion amigo_de="p3" />
    </persona>
</agenda>
